#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ok=0
need() {
  if [ -e "$1" ]; then echo "ok  $1"; else echo "MISSING  $1"; ok=1; fi
}
wait_for() {
  if [ -e "$1" ]; then echo "ok  $1"; else echo "wait $2"; fi
}
need "$ROOT/packaging/linux/install.sh"
need "$ROOT/packaging/linux/install-node22.sh"
need "$ROOT/packaging/linux/serve-and-open.mjs"
need "$ROOT/native/horizon/Makefile"
need "$ROOT/native/horizon/Godot/project.godot"
need "$ROOT/native/horizon/UE/SpectralHorizon/SpectralHorizon.uproject"
need "$ROOT/native/v01d/wayland/hyprland.conf"
need "$ROOT/native/v01d/wayland/session.sh"
need "$ROOT/public/horsemen/portal/hell.jpg"
need "$ROOT/public/horsemen/field.jpg"
need "$ROOT/public/horsemen/void-overture.mp4"
need "$ROOT/src/lib/v01d/void-score.ts"
need "$ROOT/native/horizon/UE/VoidDesktop/Shaders/AliensSlit.usf"
need "$ROOT/native/horizon/UE/VoidDesktop/Source/VoidOverture.cpp"
need "$ROOT/native/horizon/Godot/void/nebula.gdshader"
need "$ROOT/packaging/arch/boot/syslinux.cfg"
need "$ROOT/packaging/arch/boot/grub.cfg"
need "$ROOT/src/lib/v01d/firmware.ts"
need "$ROOT/src/lib/v01d/horizon.ts"
need "$ROOT/src/lib/v01d/vfs-proto.ts"
need "$ROOT/src/lib/hx/proto.ts"
need "$ROOT/src/lib/hector/cores.ts"
need "$ROOT/packaging/arch/dual-core/install.sh"
need "$ROOT/packaging/arch/dual-core/gateway.py"
need "$ROOT/packaging/arch/dual-core/verify.sh"
need "$ROOT/packaging/arch/sign.sh"
need "$ROOT/src/lib/v01d/sign.ts"
need "$ROOT/packaging/arch/dual-core/hear.sh"
need "$ROOT/packaging/arch/dual-core/pipewire-diplomat.conf"
need "$ROOT/packaging/arch/tts/server.py"
need "$ROOT/packaging/arch/tts/install_predictive_tts.sh"
need "$ROOT/packaging/arch/programs/install.sh"
need "$ROOT/native/horizon/UE/SpectralHorizon/Scripts/hector_metahuman.py"
need "$ROOT/packaging/arch/dual-core/osv01d-hear.service"
need "$ROOT/src/lib/hector/hear.ts"
need "$ROOT/src/lib/asimov/home.ts"
need "$ROOT/packaging/arch/firmware-first.sh"
need "$ROOT/native/horizon/scripts/install-stack.sh"
need "$ROOT/packaging/linux/install-os-games.sh"
need "$ROOT/packaging/cloud/bootstrap_cloud.sh"
need "$ROOT/packaging/cloud/compose.yml"
need "$ROOT/packaging/cloud/traefik/traefik.yml"
need "$ROOT/packaging/cloud/health.sh"
need "$ROOT/packaging/cloud/repair.sh"
need "$ROOT/src/lib/v01d/cloud.ts"
need "$ROOT/src/routes/api/v1/v01d/cloud.ts"
need "$ROOT/packaging/cloud/orchestrate.sh"
need "$ROOT/packaging/cloud/prometheus/alerts.yml"
need "$ROOT/packaging/cloud/prometheus/alertmanager.yml"
need "$ROOT/src/lib/v01d/orchestrate.ts"
need "$ROOT/packaging/cloud/otel/collector.yml"
need "$ROOT/src/lib/v01d/geom.ts"
need "$ROOT/packaging/cloud/restore.sh"
need "$ROOT/packaging/cloud/mesh.sh"
need "$ROOT/src/lib/v01d/pathways.ts"
need "$ROOT/native/horizon/include/hx/pathways.hpp"
need "$ROOT/packaging/wsl/setup.sh"
need "$ROOT/packaging/wsl/install.ps1"
need "$ROOT/src/lib/v01d/guide.ts"
need "$ROOT/packaging/wsl/hector-hook.sh"
need "$ROOT/src/lib/asimov/lab.ts"
need "$ROOT/src/lib/hector/rl.ts"
need "$ROOT/src/lib/hx/aether-tqc.ts"
need "$ROOT/packaging/forge/pipewire-aether.conf"
need "$ROOT/src/lib/forge/mark.ts"
need "$ROOT/packaging/forge/install.sh"
need "$ROOT/packaging/forge/realtime.conf"
need "$ROOT/public/horsemen/icons/forge.svg"
need "$ROOT/public/horsemen/void.jpg"
need "$ROOT/public/horsemen/field-dawn.jpg"
need "$ROOT/native/asimov/hal/hal.hpp"
need "$ROOT/src/lib/hector/metal.ts"
need "$ROOT/src/lib/asimov/team.ts"
need "$ROOT/src/lib/hx/rdna.ts"
need "$ROOT/src/lib/asimov/rdna.ts"
need "$ROOT/src/lib/asimov/rdna-step.ts"
need "$ROOT/packaging/asimov/install-rdna.sh"
need "$ROOT/native/asimov/rdna/step.hip"
need "$ROOT/packaging/asimov/install.sh"
need "$ROOT/packaging/asimov/install-isaac.sh"
wait_for "$ROOT/vendor/isaac/IsaacSim/VERSION" "isaac (fetch on GPU box — packaging/asimov/install-isaac.sh)"
need "$ROOT/src/components/horsemen/asimov.tsx"
need "$ROOT/packaging/wsl/hector-hook.sh"
need "$ROOT/packaging/helix/helix.sh"
need "$ROOT/packaging/linux/ghostwalk-default.sh"
need "$ROOT/src/lib/sentinel/care.ts"
need "$ROOT/src/lib/sentinel/memory.ts"
need "$ROOT/packaging/sentinel/main.py"
need "$ROOT/packaging/sentinel/install.sh"
need "$ROOT/src/lib/hx/suite.ts"
need "$ROOT/src/lib/hx/weights-repair.ts"
need "$ROOT/packaging/suite/install.sh"
wait_for "$ROOT/packaging/suite/weights/ggml-tiny.bin" "whisper tiny (packaging/suite/fetch-weights.sh)"
need "$ROOT/packaging/arch/bootstrap.sh"
need "$ROOT/packaging/arch/install-live.sh"
need "$ROOT/packaging/arch/mkiso.sh"
need "$ROOT/packaging/arch/live-boot.sh"
need "$ROOT/packaging/arch/archiso/profiledef.sh"
need "$ROOT/packaging/arch/archiso/efiboot/loader/loader.conf"
need "$ROOT/packaging/linux/fetch-images.sh"
need "$ROOT/packaging/linux/hector-open"
need "$ROOT/packaging/linux/USER.md"
need "$ROOT/packaging/linux/install-vscodium.sh"
need "$ROOT/packaging/hx/codium/.vscode/tasks.json"
need "$ROOT/packaging/hx/codium/.vscode/settings.json"
need "$ROOT/packaging/hx/CODIUM.md"
need "$ROOT/packaging/arch/install-ue.sh"
need "$ROOT/packaging/arch/install-godot.sh"
need "$ROOT/native/horizon/Godot/void/nebula.gdshader"
need "$ROOT/native/horizon/Godot/void/score.gd"
need "$ROOT/native/horizon/Godot/void/main.tscn"
need "$ROOT/native/horizon/UE/VoidDesktop/Source/VoidScore.h"
need "$ROOT/native/horizon/UE/VoidDesktop/Shaders/VoidNebula.usf"
need "$ROOT/native/horizon/scripts/install-godot.sh"
need "$ROOT/native/horizon/scripts/install-unreal.sh"
need "$ROOT/native/horizon/scripts/open-void-godot.sh"
need "$ROOT/native/horizon/scripts/open-void-unreal.sh"
need "$ROOT/native/horizon/scripts/warm-aesthetics.sh"
need "$ROOT/src/lib/v01d/downloads.ts"
need "$ROOT/src/lib/v01d/programs.ts"
need "$ROOT/src/lib/v01d/aesthetics.ts"
need "$ROOT/src/lib/v01d/codium.ts"
need "$ROOT/src/components/horsemen/hx-ide.tsx"
command -v blender >/dev/null && echo "ok  blender" || echo "wait blender (OS install)"
command -v godot >/dev/null && echo "ok  godot" || echo "wait godot (OS install)"
command -v codium >/dev/null && echo "ok  codium" || echo "wait codium (packaging/linux/install-vscodium.sh)"
wait_for "/opt/unreal/Engine/Binaries/Linux/UnrealEditor" "unreal (packaging/arch/install-ue.sh)"
wait_for "/opt/godot/Godot" "godot 4.7 zip (native/horizon/scripts/install-godot.sh)"
command -v node >/dev/null && echo "ok  node $(node -v)" || echo "MISSING  node"
exit $ok
