/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BiRouteImport } from './routes/bi'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as HxRouteImport } from './routes/hx'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as ApiShareRouteImport } from './routes/api/share'
import { Route as HxSessionRouteImport } from './routes/hx.session'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BiRoute = BiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const HxRoute = HxRouteImport.update({
  id: '/hx',
  path: '/hx',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareRoute = ApiShareRouteImport.update({
  id: '/api/share',
  path: '/api/share',
  getParentRoute: () => rootRouteImport,
} as any)
const HxSessionRoute = HxSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => HxRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bi': typeof BiRoute
  '/downloads': typeof DownloadsRoute
  '/hx': typeof HxRouteWithChildren
  '/sandbox': typeof SandboxRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/share': typeof ApiShareRoute
  '/hx/session': typeof HxSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bi': typeof BiRoute
  '/downloads': typeof DownloadsRoute
  '/hx': typeof HxRouteWithChildren
  '/sandbox': typeof SandboxRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/share': typeof ApiShareRoute
  '/hx/session': typeof HxSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bi': typeof BiRoute
  '/downloads': typeof DownloadsRoute
  '/hx': typeof HxRouteWithChildren
  '/sandbox': typeof SandboxRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/share': typeof ApiShareRoute
  '/hx/session': typeof HxSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bi'
    | '/downloads'
    | '/hx'
    | '/sandbox'
    | '/api/rtc'
    | '/api/share'
    | '/hx/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bi'
    | '/downloads'
    | '/hx'
    | '/sandbox'
    | '/api/rtc'
    | '/api/share'
    | '/hx/session'
  id:
    | '__root__'
    | '/'
    | '/bi'
    | '/downloads'
    | '/hx'
    | '/sandbox'
    | '/api/rtc'
    | '/api/share'
    | '/hx/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiRoute: typeof BiRoute
  DownloadsRoute: typeof DownloadsRoute
  HxRoute: typeof HxRouteWithChildren
  SandboxRoute: typeof SandboxRoute
  ApiRtcRoute: typeof ApiRtcRoute
  ApiShareRoute: typeof ApiShareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bi': {
      id: '/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof BiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hx': {
      id: '/hx'
      path: '/hx'
      fullPath: '/hx'
      preLoaderRoute: typeof HxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share': {
      id: '/api/share'
      path: '/api/share'
      fullPath: '/api/share'
      preLoaderRoute: typeof ApiShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hx/session': {
      id: '/hx/session'
      path: '/session'
      fullPath: '/hx/session'
      preLoaderRoute: typeof HxSessionRouteImport
      parentRoute: typeof HxRoute
    }
  }
}

interface HxRouteChildren {
  HxSessionRoute: typeof HxSessionRoute
}

const HxRouteChildren: HxRouteChildren = {
  HxSessionRoute: HxSessionRoute,
}

const HxRouteWithChildren = HxRoute._addFileChildren(HxRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiRoute: BiRoute,
  DownloadsRoute: DownloadsRoute,
  HxRoute: HxRouteWithChildren,
  SandboxRoute: SandboxRoute,
  ApiRtcRoute: ApiRtcRoute,
  ApiShareRoute: ApiShareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
