/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BiRouteImport } from './routes/bi'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as HxRouteImport } from './routes/hx'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as ApiShareRouteImport } from './routes/api/share'
import { Route as HxSessionRouteImport } from './routes/hx.session'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1CloudRouteImport } from './routes/api/v1/cloud'
import { Route as ApiV1EmbeddingsRouteImport } from './routes/api/v1/embeddings'
import { Route as ApiV1ExtensionsRouteImport } from './routes/api/v1/extensions'
import { Route as ApiV1FunctionsRouteImport } from './routes/api/v1/functions'
import { Route as ApiV1McpRouteImport } from './routes/api/v1/mcp'
import { Route as ApiV1ModelsRouteImport } from './routes/api/v1/models'
import { Route as ApiV1ShareRouteImport } from './routes/api/v1/share'
import { Route as ApiV1SpoolRouteImport } from './routes/api/v1/spool'
import { Route as ApiV1ChatCompletionsRouteImport } from './routes/api/v1/chat/completions'
import { Route as ApiV1HostWslRouteImport } from './routes/api/v1/host/wsl'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BiRoute = BiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const HxRoute = HxRouteImport.update({
  id: '/hx',
  path: '/hx',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareRoute = ApiShareRouteImport.update({
  id: '/api/share',
  path: '/api/share',
  getParentRoute: () => rootRouteImport,
} as any)
const HxSessionRoute = HxSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => HxRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CloudRoute = ApiV1CloudRouteImport.update({
  id: '/api/v1/cloud',
  path: '/api/v1/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EmbeddingsRoute = ApiV1EmbeddingsRouteImport.update({
  id: '/api/v1/embeddings',
  path: '/api/v1/embeddings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ExtensionsRoute = ApiV1ExtensionsRouteImport.update({
  id: '/api/v1/extensions',
  path: '/api/v1/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FunctionsRoute = ApiV1FunctionsRouteImport.update({
  id: '/api/v1/functions',
  path: '/api/v1/functions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1McpRoute = ApiV1McpRouteImport.update({
  id: '/api/v1/mcp',
  path: '/api/v1/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ModelsRoute = ApiV1ModelsRouteImport.update({
  id: '/api/v1/models',
  path: '/api/v1/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ShareRoute = ApiV1ShareRouteImport.update({
  id: '/api/v1/share',
  path: '/api/v1/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SpoolRoute = ApiV1SpoolRouteImport.update({
  id: '/api/v1/spool',
  path: '/api/v1/spool',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ChatCompletionsRoute = ApiV1ChatCompletionsRouteImport.update({
  id: '/api/v1/chat/completions',
  path: '/api/v1/chat/completions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HostWslRoute = ApiV1HostWslRouteImport.update({
  id: '/api/v1/host/wsl',
  path: '/api/v1/host/wsl',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bi': typeof BiRoute
  '/chat': typeof ChatRoute
  '/downloads': typeof DownloadsRoute
  '/hx': typeof HxRouteWithChildren
  '/login': typeof LoginRoute
  '/sandbox': typeof SandboxRoute
  '/verify': typeof VerifyRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/share': typeof ApiShareRoute
  '/hx/session': typeof HxSessionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/cloud': typeof ApiV1CloudRoute
  '/api/v1/embeddings': typeof ApiV1EmbeddingsRoute
  '/api/v1/extensions': typeof ApiV1ExtensionsRoute
  '/api/v1/functions': typeof ApiV1FunctionsRoute
  '/api/v1/mcp': typeof ApiV1McpRoute
  '/api/v1/models': typeof ApiV1ModelsRoute
  '/api/v1/share': typeof ApiV1ShareRoute
  '/api/v1/spool': typeof ApiV1SpoolRoute
  '/api/v1/chat/completions': typeof ApiV1ChatCompletionsRoute
  '/api/v1/host/wsl': typeof ApiV1HostWslRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bi': typeof BiRoute
  '/chat': typeof ChatRoute
  '/downloads': typeof DownloadsRoute
  '/hx': typeof HxRouteWithChildren
  '/login': typeof LoginRoute
  '/sandbox': typeof SandboxRoute
  '/verify': typeof VerifyRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/share': typeof ApiShareRoute
  '/hx/session': typeof HxSessionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/cloud': typeof ApiV1CloudRoute
  '/api/v1/embeddings': typeof ApiV1EmbeddingsRoute
  '/api/v1/extensions': typeof ApiV1ExtensionsRoute
  '/api/v1/functions': typeof ApiV1FunctionsRoute
  '/api/v1/mcp': typeof ApiV1McpRoute
  '/api/v1/models': typeof ApiV1ModelsRoute
  '/api/v1/share': typeof ApiV1ShareRoute
  '/api/v1/spool': typeof ApiV1SpoolRoute
  '/api/v1/chat/completions': typeof ApiV1ChatCompletionsRoute
  '/api/v1/host/wsl': typeof ApiV1HostWslRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bi': typeof BiRoute
  '/chat': typeof ChatRoute
  '/downloads': typeof DownloadsRoute
  '/hx': typeof HxRouteWithChildren
  '/login': typeof LoginRoute
  '/sandbox': typeof SandboxRoute
  '/verify': typeof VerifyRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/share': typeof ApiShareRoute
  '/hx/session': typeof HxSessionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/cloud': typeof ApiV1CloudRoute
  '/api/v1/embeddings': typeof ApiV1EmbeddingsRoute
  '/api/v1/extensions': typeof ApiV1ExtensionsRoute
  '/api/v1/functions': typeof ApiV1FunctionsRoute
  '/api/v1/mcp': typeof ApiV1McpRoute
  '/api/v1/models': typeof ApiV1ModelsRoute
  '/api/v1/share': typeof ApiV1ShareRoute
  '/api/v1/spool': typeof ApiV1SpoolRoute
  '/api/v1/chat/completions': typeof ApiV1ChatCompletionsRoute
  '/api/v1/host/wsl': typeof ApiV1HostWslRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bi'
    | '/chat'
    | '/downloads'
    | '/hx'
    | '/login'
    | '/sandbox'
    | '/verify'
    | '/api/rtc'
    | '/api/share'
    | '/hx/session'
    | '/api/auth/$'
    | '/api/v1/cloud'
    | '/api/v1/embeddings'
    | '/api/v1/extensions'
    | '/api/v1/functions'
    | '/api/v1/mcp'
    | '/api/v1/models'
    | '/api/v1/share'
    | '/api/v1/spool'
    | '/api/v1/chat/completions'
    | '/api/v1/host/wsl'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bi'
    | '/chat'
    | '/downloads'
    | '/hx'
    | '/login'
    | '/sandbox'
    | '/verify'
    | '/api/rtc'
    | '/api/share'
    | '/hx/session'
    | '/api/auth/$'
    | '/api/v1/cloud'
    | '/api/v1/embeddings'
    | '/api/v1/extensions'
    | '/api/v1/functions'
    | '/api/v1/mcp'
    | '/api/v1/models'
    | '/api/v1/share'
    | '/api/v1/spool'
    | '/api/v1/chat/completions'
    | '/api/v1/host/wsl'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bi'
    | '/chat'
    | '/downloads'
    | '/hx'
    | '/login'
    | '/sandbox'
    | '/verify'
    | '/api/rtc'
    | '/api/share'
    | '/hx/session'
    | '/api/auth/$'
    | '/api/v1/cloud'
    | '/api/v1/embeddings'
    | '/api/v1/extensions'
    | '/api/v1/functions'
    | '/api/v1/mcp'
    | '/api/v1/models'
    | '/api/v1/share'
    | '/api/v1/spool'
    | '/api/v1/chat/completions'
    | '/api/v1/host/wsl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BiRoute: typeof BiRoute
  ChatRoute: typeof ChatRoute
  DownloadsRoute: typeof DownloadsRoute
  HxRoute: typeof HxRouteWithChildren
  LoginRoute: typeof LoginRoute
  SandboxRoute: typeof SandboxRoute
  VerifyRoute: typeof VerifyRoute
  ApiRtcRoute: typeof ApiRtcRoute
  ApiShareRoute: typeof ApiShareRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1CloudRoute: typeof ApiV1CloudRoute
  ApiV1EmbeddingsRoute: typeof ApiV1EmbeddingsRoute
  ApiV1ExtensionsRoute: typeof ApiV1ExtensionsRoute
  ApiV1FunctionsRoute: typeof ApiV1FunctionsRoute
  ApiV1McpRoute: typeof ApiV1McpRoute
  ApiV1ModelsRoute: typeof ApiV1ModelsRoute
  ApiV1ShareRoute: typeof ApiV1ShareRoute
  ApiV1SpoolRoute: typeof ApiV1SpoolRoute
  ApiV1ChatCompletionsRoute: typeof ApiV1ChatCompletionsRoute
  ApiV1HostWslRoute: typeof ApiV1HostWslRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bi': {
      id: '/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof BiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hx': {
      id: '/hx'
      path: '/hx'
      fullPath: '/hx'
      preLoaderRoute: typeof HxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share': {
      id: '/api/share'
      path: '/api/share'
      fullPath: '/api/share'
      preLoaderRoute: typeof ApiShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hx/session': {
      id: '/hx/session'
      path: '/session'
      fullPath: '/hx/session'
      preLoaderRoute: typeof HxSessionRouteImport
      parentRoute: typeof HxRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/cloud': {
      id: '/api/v1/cloud'
      path: '/api/v1/cloud'
      fullPath: '/api/v1/cloud'
      preLoaderRoute: typeof ApiV1CloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/embeddings': {
      id: '/api/v1/embeddings'
      path: '/api/v1/embeddings'
      fullPath: '/api/v1/embeddings'
      preLoaderRoute: typeof ApiV1EmbeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/extensions': {
      id: '/api/v1/extensions'
      path: '/api/v1/extensions'
      fullPath: '/api/v1/extensions'
      preLoaderRoute: typeof ApiV1ExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/functions': {
      id: '/api/v1/functions'
      path: '/api/v1/functions'
      fullPath: '/api/v1/functions'
      preLoaderRoute: typeof ApiV1FunctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/mcp': {
      id: '/api/v1/mcp'
      path: '/api/v1/mcp'
      fullPath: '/api/v1/mcp'
      preLoaderRoute: typeof ApiV1McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/models': {
      id: '/api/v1/models'
      path: '/api/v1/models'
      fullPath: '/api/v1/models'
      preLoaderRoute: typeof ApiV1ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/share': {
      id: '/api/v1/share'
      path: '/api/v1/share'
      fullPath: '/api/v1/share'
      preLoaderRoute: typeof ApiV1ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/spool': {
      id: '/api/v1/spool'
      path: '/api/v1/spool'
      fullPath: '/api/v1/spool'
      preLoaderRoute: typeof ApiV1SpoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/chat/completions': {
      id: '/api/v1/chat/completions'
      path: '/api/v1/chat/completions'
      fullPath: '/api/v1/chat/completions'
      preLoaderRoute: typeof ApiV1ChatCompletionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/host/wsl': {
      id: '/api/v1/host/wsl'
      path: '/api/v1/host/wsl'
      fullPath: '/api/v1/host/wsl'
      preLoaderRoute: typeof ApiV1HostWslRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HxRouteChildren {
  HxSessionRoute: typeof HxSessionRoute
}

const HxRouteChildren: HxRouteChildren = {
  HxSessionRoute: HxSessionRoute,
}

const HxRouteWithChildren = HxRoute._addFileChildren(HxRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BiRoute: BiRoute,
  ChatRoute: ChatRoute,
  DownloadsRoute: DownloadsRoute,
  HxRoute: HxRouteWithChildren,
  LoginRoute: LoginRoute,
  SandboxRoute: SandboxRoute,
  VerifyRoute: VerifyRoute,
  ApiRtcRoute: ApiRtcRoute,
  ApiShareRoute: ApiShareRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1CloudRoute: ApiV1CloudRoute,
  ApiV1EmbeddingsRoute: ApiV1EmbeddingsRoute,
  ApiV1ExtensionsRoute: ApiV1ExtensionsRoute,
  ApiV1FunctionsRoute: ApiV1FunctionsRoute,
  ApiV1McpRoute: ApiV1McpRoute,
  ApiV1ModelsRoute: ApiV1ModelsRoute,
  ApiV1ShareRoute: ApiV1ShareRoute,
  ApiV1SpoolRoute: ApiV1SpoolRoute,
  ApiV1ChatCompletionsRoute: ApiV1ChatCompletionsRoute,
  ApiV1HostWslRoute: ApiV1HostWslRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
