[global]
   workgroup = V01D
   server string = OS V01D
   map to guest = never
   smb ports = 445
   min protocol = SMB3
   smb encrypt = desired

[Files]
   path = /v01d/home
   browseable = yes
   read only = no
   guest ok = no

[Pictures]
   path = /v01d/home/Pictures
   browseable = yes
   read only = no
   guest ok = no

[Media]
   path = /v01d/media
   browseable = yes
   read only = no
   guest ok = no

[Programs]
   path = /v01d/programs
   browseable = yes
   read only = yes
   guest ok = no
